swagger: "2.0"
info:
  title: "Ecommerce API"
  version: "1.0"
  description: "API"
  contact:
    name: "API"
    email: puyaars@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:4000
schemes:
  - "http"

responses:
  200:
    description: "Success"
  400:
    description: "Bad Request"
  401:
    description: "Unauthorized"
  404:
    description: "Not Found"
  500:
    description: "Internal Server Error"

paths:
  /api:
    get:
      summary: "health check"
      description: "if the api is working correctly it will return 200"
      responses: "200"
